#!/bin/bash
#SBATCH --job-name=sw_check
#SBATCH --partition=mit_preemptable
#SBATCH --nodes=1
#SBATCH --ntasks=21
#SBATCH --cpus-per-task=1
#SBATCH --mem=120G
#SBATCH --time=08:00:00
#SBATCH --array=0-3%4
#SBATCH --requeue
#SBATCH --output=logs/sw_%A_%a.out
#SBATCH --error=logs/sw_%A_%a.err

# Generated by hullsweep/make_batch.py -- edit the .in template, not this file.
#
# One array task = one captive case (manifest row == SLURM_ARRAY_TASK_ID).
# %4 caps simultaneous tasks: the Shared Web entitlement is
# 25 CFD tasks + 32 HPC per-core licenses for the WHOLE account, so the cap
# is set by HPC cores per job, not by nodes. Check licdebug after the first
# wave (grep HPC_PARALLEL) before raising it.
#
# Preemption: --requeue restarts the task; run_sweep_case.py resumes from
# the newest autosave in the per-CASE work dir.

set -euo pipefail

source "$HOME/ansys_env.sh"

export SWEEP_ROOT="$HOME/orcd/pool/hullsweep/check"
MANIFEST="$SWEEP_ROOT/manifest.csv"
ID="${SLURM_ARRAY_TASK_ID}"

CASE_ID=$(awk -F, -v id="$ID" 'NR>1 && $1==id {print $2}' "$MANIFEST")
if [ -z "$CASE_ID" ]; then
    echo "FATAL: no manifest row with index $ID" >&2
    exit 1
fi

export HULL_CASE="$SWEEP_ROOT/cases/${CASE_ID}.cas.h5"
export HULL_SIDECAR="$SWEEP_ROOT/cases/${CASE_ID}.json"
if [ -r "$SWEEP_ROOT/cases/${CASE_ID}.dat.h5" ]; then
    export HULL_DATA="$SWEEP_ROOT/cases/${CASE_ID}.dat.h5"
else
    export HULL_DATA=""
fi
for f in "$HULL_CASE" "$HULL_SIDECAR"; do
    [ -r "$f" ] || { echo "FATAL: not readable: $f" >&2; exit 1; }
done

# Per CASE (not per job id) so a requeued task finds its own autosaves.
export HULL_WORKDIR="$HOME/orcd/scratch/hullsweep/check/$CASE_ID"
export HULL_KEEP_DIR="$HOME/hull_results/hullsweep/check/$CASE_ID"
mkdir -p "$HULL_WORKDIR"

echo "job      : ${SLURM_ARRAY_JOB_ID}_${ID} (restart count ${SLURM_RESTART_COUNT:-0})"
echo "node     : $SLURM_JOB_NODELIST   ntasks: $SLURM_NTASKS"
echo "case     : $CASE_ID"

# --- Licensing: Shared Web via CA-bundle bind mount (from submit_hull.sh) ---
# LOAD-BEARING. ansyscl ignores SSL_CERT_FILE and reads
# /etc/pki/tls/certs/ca-bundle.crt, which on Rocky 8 lacks Sectigo Root R46.
export CA_BUNDLE="$HOME/ansys_ca_bundle.pem"
export CA_TARGET="/etc/pki/tls/certs/ca-bundle.crt"
export CA_EXPECTED_CERTS=289
[ -r "$CA_BUNDLE" ] || { echo "FATAL: merged CA bundle not found: $CA_BUNDLE" >&2; exit 1; }

if [ "$SLURM_JOB_NUM_NODES" -gt 1 ]; then
    echo "FATAL: multi-node unsupported (mount namespace is per node)." >&2
    exit 1
fi

export HULL_UI_MODE="no_gui_or_graphics"

# Walltime handling: the driver stops HULL_STOP_MARGIN_S before the job's end,
# writes its data, and reports state "incomplete"; this script then requeues
# the task, which resumes from that file. A walltime KILL is not requeued.
END_ISO=$(squeue -h -j "$SLURM_JOB_ID" -o %e)
export HULL_DEADLINE_EPOCH=$(date -d "$END_ISO" +%s)
echo "deadline : $END_ISO"
MAX_RESTARTS=12
export HULL_EXPORT=0

module load miniforge
set +u
conda activate pyfluent
set -u

cd "$HULL_WORKDIR"

unshare -r --mount bash -c '
    set -euo pipefail
    mount --bind "$CA_BUNDLE" "$CA_TARGET"
    ns_certs=$(grep -c "BEGIN CERTIFICATE" "$CA_TARGET")
    if [ "$ns_certs" -ne "$CA_EXPECTED_CERTS" ]; then
        echo "FATAL: bind mount did not take ($ns_certs certs)." >&2
        exit 1
    fi
    exec python "$SWEEP_ROOT/run_sweep_case.py"
'

STATE=$(python -c "import json;print(json.load(open('$HULL_WORKDIR/status.json'))['state'])" 2>/dev/null || echo unknown)
echo "state    : $STATE"
if [ "$STATE" = "incomplete" ]; then
    if [ "${SLURM_RESTART_COUNT:-0}" -ge "$MAX_RESTARTS" ]; then
        echo "FATAL: $MAX_RESTARTS restarts reached; not requeueing." >&2
        exit 1
    fi
    echo "requeueing ${SLURM_ARRAY_JOB_ID}_${ID} to continue"
    scontrol requeue "${SLURM_ARRAY_JOB_ID}_${ID}"
fi

echo "done: $(date)"
